### ISSUE TITLE
--disable-device-emulation doesn't work 

### ISSUE THREAD

**Issue by shchav1a** [mikestead/lighthouse-batch#13]
default device emulation switch from https://github.com/GoogleChrome/lighthouse  doesn't work in lighthouse-batch

**Comment by mikestead** [comment]
@shchav1a can you clarify how you were calling lighthouse batch? This should work

`lighthouse-batch -s https://housing.com -p "--disable-device-emulation"`

Note that in v5+ of lighthouse this command has been replaced with `--emulated-form-factor=none`

**Comment by evdama** [comment]
really usefull package, thanks...
regarding the issue:

I can confirm it works as I'm using a line in my package.json that looks like this
`lighthouse-batch --html --params \"--view --throttling-method=provided --emulated-form-factor=desktop\" --file ./tests/lighthouse/edm_routes.txt --out ./tests/lighthouse/report/desktop`

**Comment by shchav1a** [comment]
Thanks for update guys. No longer and issue for me as well. Closing as resolved.

**Comment by DylanCDuke** [comment]
Hi all - not sure this has to be reopened, probably user error but hoping someone can help. 

I'm not able to get `--emulated-form-factor=desktop` to work correctly. I'm passing as below:

`lighthouse-batch -h -v -s <url> --params "--chrome-flags=\"--no-sandbox --disable-gpu --emulated-form-factor=desktop\""`

I'm including the --chrome-flags to avoid headless to verify this is running desktop, but the window still displays as mobile.  Any ideas on how I could be using this incorrectly?

**Comment by DylanCDuke** [comment]
> Hi all - not sure this has to be reopened, probably user error but hoping someone can help.
> 
> I'm not able to get `--emulated-form-factor=desktop` to work correctly. I'm passing as below:
> 
> `lighthouse-batch -h -v -s <url> --params "--chrome-flags=\"--no-sandbox --disable-gpu --emulated-form-factor=desktop\""`
> 
> I'm including the --chrome-flags to avoid headless to verify this is running desktop, but the window still displays as mobile. Any ideas on how I could be using this incorrectly?

I've also tried a few different forms of this as well.
'--params "--chrome-flags=\"--emulated-form-factor=desktop\""'
'--params --emulated-form-factor=desktop'
Among others
