### ISSUE TITLE
Getting JScript compilation error on Windows 10 

### ISSUE THREAD

**Issue by kjackey1** [mikestead/lighthouse-batch#15]
Getting JScript compilation error on Windows 10 
![2019-04-11 10_23_28-Windows Script Host](https://user-images.githubusercontent.com/17477948/55965145-fd13ac80-5c43-11e9-9d6e-d1bd89aa71aa.png)

Read suggestions stating to try using the -g parameter as well (ex: lighthouse-batch -s https://airhorner.com,https://housing.com -g), however that gives a "Global instance not found" and then the same error again: 
![2019-04-11 10_26_15-](https://user-images.githubusercontent.com/17477948/55965309-58de3580-5c44-11e9-8746-0651b48a694a.png)

**Comment by elsassph** [comment]
Sounds like the tool isn't executed by node - that won't work.

Are `node` and `npm` in your PATH? You may need to reinstall NodeJS.

**Comment by tommytusj** [comment]
I have the same error on Windows 10. Using the -v for verbose logging shows some debug suggesting paths are wrong on windows

`Lighthouse batch run begin for 1 site
1/1: Lighthouse analyzing 'https://www.google.com'
"https://www.google.com" --output json --output html --output-path "c:\lighthousetest\report/www_google_com" null
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'c:\lighthousetest\report/www_google_com.report.json'`

**Comment by elsassph** [comment]
Does `report` folder exist? If not, try creating it before running the tool.

**Comment by tommytusj** [comment]
yes. The folders are created

**Comment by mikestead** [comment]
@tommytusj thanks for the details, I've released `v4.0.1` which should sort out windows pathing. Can you report back if you're still seeing issues and I can reopen.

**Comment by mikestead** [comment]
And @elsassph thanks for helping out

**Comment by leptest** [comment]
Thanks @mikestead for looking at this earlier. I've been having similar issues.
```
windows: 10.1803
node: 10.15.3
npm: 6.9.0
lighthouse-batch: 4.0.1
```

Same issues as others with windows trying to open the JS file. Setting windows to use node by default to open JS files got me past that issue.

Then i got hit with the `Error: ENOENT: no such file or directory`. Not sure how i got past that one..

But now we're onto a different error:
```
> lighthouse-batch -s https://airhorner.com,https://housing.com

Please provide a url

Specify --help for available options
1/2: Lighthouse analysis FAILED for https://airhorner.com
Please provide a url

Specify --help for available options
2/2: Lighthouse analysis FAILED for https://housing.com
```

I'm assuming these issues are related..  Let me know if there is anything else i can do to help narrow down the problem.

**Comment by tommytusj** [comment]
Im assuming this won’t run on Windows and just installed WSL on Windows 10 and ran it there :)

**Comment by mikestead** [comment]
@leptest cheers, I'll have a look this weekend and report back. If no luck then it may need to wait until I can get hold of a windows machine next week.

**Comment by mikestead** [comment]
@leptest @tommytusj I've just cut `v4.1.0` with a fix from @elsassph. When you get min can you double check this works ok for you and report back? I'll reopen this for now until we're confident.

**Comment by tommytusj** [comment]
@mikestead I've just tried 5.0.1 and it works in Windows 10! nice work
