### ISSUE TITLE
Paypal

### ISSUE THREAD

**Issue by thomwatson** [mikestead/lighthouse-batch#26]
What's your PayPal Mike? Would like to send you a coffee. LHB has been a huge help to me over the last 6 months.

**Comment by mikestead** [comment]
@thomwatson that's very kind and appreciated! The thanks is more than enough. If you like then feel free to add an extra $ next time you're donating to a good cause. 👍

**Comment by thomwatson** [comment]
@mikestead no problem, shall do. Thanks again!
