### ISSUE TITLE
Supporting threshold as in lighthouse-ci

### ISSUE THREAD

**Issue by pun-ky** [mikestead/lighthouse-batch#29]
https://github.com/andreasonny83/lighthouse-ci

ideally, if this tool will  also support parameters causing returning success or fail in case of exceeded threshold values.

imagine:
```
    $ lighthouse-batch -s https://example.com,http://demo.example.com --score=75
    $ lighthouse-batch -s https://example.com,http://demo.example.com --accessibility=90 --seo=80
    $ lighthouse-batch -s https://example.com,http://demo.example.com --accessibility=90 --seo=80 --report=folder
    $ lighthouse-batch https://example.com,http://demo.example.com --report=folder --config-path=configs.json
```

this matters because I'd like to include using this tool lighthouse-batch in my build in case of checking many site pages and also considering thresholds. to get immediate feedback / "sth is wrong in one of my pages in case of performance"

what do you think?

**Comment by evdama** [comment]
that makes total sense because when there's an issue and you run into a timeout for example, that's a nice way to get notified and not have to wait rather long until something in your hosting environment times out and thus lighthouse errors

**Comment by mikestead** [comment]
This would be great. I don't have time to look at this (as you may have guessed), but open to PRs if anyone has some time and the inclination.

**Comment by mikestead** [comment]
Support added in lighthouse-batch `v7.1.0`

**Comment by pun-ky** [comment]
thanks, however, some time ago I created - [https://github.com/wttech/gradle-lighthouse-plugin](https://github.com/wttech/gradle-lighthouse-plugin) (using lighthouse-ci internally) in which I am already checking these budgets :)
