### ISSUE TITLE
How can I connect with Jenkins using lighthouse-batch

### ISSUE THREAD

**Issue by MohamedRasool786** [mikestead/lighthouse-batch#3]
Is there any Pipeline scripts used in Jenkins using lighthouse-batch

**Comment by mikestead** [comment]
Hey @MohamedRasool786 this tools is a simple CLI to batch Lighthouse and agnostic to CI tools.

You should be able to execute it on an agent if Chrome's installed. At the moment it doesn't support headless chrome.

**Comment by ain** [comment]
I believe https://github.com/mikestead/lighthouse-batch/blob/master/README.md#notes denotes that it does support headless Chrome now. 

I was not able to get it working on GitHub Actions either though, despite `CHROME_PATH` exclusively set. It failed with:

```
...
Fri, 10 May 2019 12:59:23 GMT ChromeLauncher Waiting for browser.......................................................................................................
Fri, 10 May 2019 12:59:23 GMT ChromeLauncher:error connect ECONNREFUSED 127.0.0.1:42395
Fri, 10 May 2019 12:59:23 GMT ChromeLauncher:error Logging contents of /tmp/lighthouse.hh8qq92/chrome-err.log
Fri, 10 May 2019 12:59:23 GMT ChromeLauncher:error [0510/125858.298943:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```
