### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by kevsersrca** [mikestead/lighthouse-batch#31]
when running this program, I deleted all files in the output parameter and I could not bring back. Please fıx the bugs. 

This section:
https://github.com/mikestead/lighthouse-batch/blob/52a59d10119ee6d80c85fcd9d1dd421d45cea014/index.js#L21

**Comment by kevsersrca** [comment]
@mikestead

**Comment by mikestead** [comment]
@kevsersrca deeply sorry you ran into this and apologies for not replying sooner. A fix was released for this in Feb of this year.
