### ISSUE TITLE
Separate Audits declared in params

### ISSUE THREAD

**Issue by sean-zero1** [mikestead/lighthouse-batch#34]
Hi, 

I'm wondering if it's possible to declare each of the reports Lighthouse generates separately. E.g...

lighthouse-batch -f urls.txt --html - "--perf"

runs a performance only audit (although that seems to fail and generates all)
Is it possible to run an SEO / Accessibility / Best Practices audit separately? Something like...

lighthouse-batch -f urls.txt --html - "--acce"

**Comment by mikestead** [comment]
Sorry I'm not going to have time to look into this. Going to close as a bit stale now but open to PRs if anyone is keen.
