### ISSUE TITLE
lighthouse-batch reports.

### ISSUE THREAD

**Issue by FahdJamy** [mikestead/lighthouse-batch#36]
**Question**
Is there any option that I could use to prevent the creation of reports.
Because I found my self not needing them.

**Suggestion**
Couldn't there be a flag I use to only display the metrics to my pages in my terminal?

**Extra question**
How can I set a minimal score (threshold) for my performance/pwa/best-practice/best-practices for the CI to pass?

**Comment by mikestead** [comment]
I've added some options to the cli see https://github.com/mikestead/lighthouse-batch/pull/43

As for CI. You can easily read the summary report in a CI script to decide whether to pass or fail. 

We could look at setting a threshold across all sites run that must be hit or exit with error code. Open to a PRs if this is what you're thinking.
