### ISSUE TITLE
Lighthouse-batch is wiping everything with rm -rf

### ISSUE THREAD

**Issue by daniel-tikken** [mikestead/lighthouse-batch#37]
Hi,

Tested out your repo, and ran this command:
<img width="764" alt="Screen Shot 2020-02-16 at 11 27 44" src="https://user-images.githubusercontent.com/57204512/74603116-53e1e200-50b0-11ea-8bed-8d2cdb6d0253.png">

Why is it doing RM? It wiped 80% of my projects..

In your docs you're stating:
 -o, --out [out]        the output folder to place reports, defaults to './report/lighthouse'
-s, --sites [sites]    a comma delimited list of site urls to analyze with Lighthouse

I never expected the rm.

But in your code at line 21 in index.js:

```
  rm('-rf', out)
```

This got me very frustrated, not even a heads up about wiping the whole folder. I'd expect a new folder to be created, not that everything gets deleted and then a new one generated?

**Comment by mikestead** [comment]
@daniel-tikken that is a bad one, super sorry for the impact it's had for you and understand you'd be more than very frustrated.

It was purely based on the use case of spitting it out to a specific directly, but it should never have been missed. I'll get this fixed asap and am once again really sorry

**Comment by mikestead** [comment]
Fix released under `v5.0.2`

**Comment by daniel-tikken** [comment]
Thanks! I appreciate it.
