### ISSUE TITLE
Lighthouse-batch

### ISSUE THREAD

**Issue by Preethi0689** [mikestead/lighthouse-batch#39]
I wish to understand how to use lighthouse batch for the entire website where we will be using login authentication and also doing some selection kind of. We see examples for static websites only.It will be very much helpful if we have a sample.Thanks in Advance.

**Comment by mikestead** [comment]
Hey @Preethi0689 sorry this sounds more like a general lighthouse question, or maybe even a selenium / puppeteer thing
