### ISSUE TITLE
Update to Lighthouse 3.x

### ISSUE THREAD

**Issue by paulirish** [mikestead/lighthouse-batch#5]
Lots has changed and we'd love to make sure folks using lh-batch get all the latest and greatest.

For you, you'll have to tweak your `getAverageScore` method. `reportCategories` to `categories`, but that should be it. https://developers.google.com/web/tools/lighthouse/v3/migration

**Comment by mikestead** [comment]
Thanks for the prompt and pointers @paulirish. I've just released an update with the latest lighthouse.
