### ISSUE TITLE
Can I specify the test on mobile instead of desktop

### ISSUE THREAD

**Issue by macnux** [mikestead/lighthouse-batch#51]
Hi,

Can I specify the test on mobile instead of desktop?

Regards,

**Comment by YoamFarges** [comment]
Lighthouse-batch is basically just a wrapper for https://github.com/GoogleChrome/lighthouse and you can specify parameters that will be passed to lighthouse (as specified in the README under "options" :  `"-p, --params <params>  extra parameters to pass to lighthouse cli for each execution e.g. -p "--perf --quiet""`)

To launch on mobile you then just have to do :
`lighthouse-batch  -p "--emulated-form-factor mobile"`

**Comment by mikestead** [comment]
Thanks for answering @YoamFarges

**Comment by topada** [comment]
Update with v7
https://github.com/GoogleChrome/lighthouse/blob/master/docs/emulation.md

`lighthouse-batch -p "--formFactor mobile"`
