### ISSUE TITLE
Error when output CSV 

### ISSUE THREAD

**Issue by ast-hao** [mikestead/lighthouse-batch#55]
Hi mikestead,

When I tried to export the .csv format by using following command, an error occurs
`lighthouse-batch -p --output=csv -s https://www.google.com`
![image](https://user-images.githubusercontent.com/77451683/104614310-84365580-565e-11eb-8d4c-a3913771f175.png)

This will impact a batch processing when I read list from site.txt.
E.g., in site.txt, following URLs are listed:
https://www.google.com
https://www.bing.com
Then, when try to use following command, the error will occur and interrupt the next URL's process.
`lighthouse-batch -p --output=csv -f D:\site.txt`

But the JSON file is actually existing.
![image](https://user-images.githubusercontent.com/77451683/104614474-aaf48c00-565e-11eb-9d1f-1b75459ea60e.png)

The `--output=csv` is supported in "lighthouse", by using this, the output csv files is easy to be imported and proceeding in a pivot table in excel, especially multi URLs existing.
So, if this can be supported in "lighthouse-batch", will be a GREAT improvement.

![image](https://user-images.githubusercontent.com/77451683/104615096-42f27580-565f-11eb-9244-54cd24953526.png)

Thanks again for providing the resource and package.

**Comment by mikestead** [comment]
Fixed in version `7.0.0` 

Use the new `--csv` option e.g. `npx lighthouse-batch --csv -s https://www.google.com`

**Comment by ast-hao** [comment]
> Fixed in version `7.0.0`
> 
> Use the new `--csv` option e.g. `npx lighthouse-batch --csv -s https://www.google.com`

Thank you Mikestead!
