### ISSUE TITLE
--params fails when passing --preset=desktop

### ISSUE THREAD

**Issue by scottprugh** [mikestead/lighthouse-batch#56]
The following cmd line fails:

lighthouse-batch -f site.txt -h -p "--preset=desktop"

Invalid values:
  Argument: preset, Given: "desktop", Choices: "perf", "experimental"

But this lighthouse command line :
lighthouse https://www.xxxx.com/ --output=json,html --preset=desktop

Is lighthouse-batch using a different version of the lighthouse library?

Succeeds.  As such I am unable to run lighthouse-batch for desktop workloads.

**Comment by ast-hao** [comment]
Try following way. It is working well at my side.
`lighthouse-batch -p "--emulated-form-factor mobile" –f site.txt -h`

**Comment by scottprugh** [comment]
Ok.  That works.  It's odd that this parameter doesn't match the lighthouse 7.0 parameters:
calling lighthouse with --emulated-form-factor desktop fails with this.
Error: Invalid emulation flag. Emulation configuration changed in LH 7.0. See https://github.com/GoogleChrome/lighthouse/blob/master/docs/emulation.md

**Comment by ast-hao** [comment]
> Thank you. That works. It's odd that this parameter doesn't match the lighthouse 7.0 parameters:
> calling lighthouse with --emulated-form-factor desktop fails with this.
> Error: Invalid emulation flag. Emulation configuration changed in LH 7.0. See https://github.com/GoogleChrome/lighthouse/blob/master/docs/emulation.md

Felt same. there are also some parameters not supported, e.g. `--output=csv`
Ref.[https://github.com/mikestead/lighthouse-batch/issues/55](url)

**Comment by mikestead** [comment]
Hey thanks all, will try and look at this soon. `lighthouse-batch` is not currently targeting lighthouse v7 so that is probably the issue. https://github.com/mikestead/lighthouse-batch/blob/master/package.json#L21

**Comment by mikestead** [comment]
Fixed in version `7.0.0` e.g. `npx lighthouse-batch -s web.dev -h -p "--preset=desktop"`

**Comment by ast-hao** [comment]
> Hey thanks all, will try and look at this soon. `lighthouse-batch` is not currently targeting lighthouse v7 so that is probably the issue. https://github.com/mikestead/lighthouse-batch/blob/master/package.json#L21

Hi mikestead,

It seems although the -p "--preset=desktop" is applied, the run is still using the mobile.
![image](https://user-images.githubusercontent.com/77451683/106407370-41240280-6412-11eb-9509-2a0d671c5094.png)
![image](https://user-images.githubusercontent.com/77451683/106407383-46814d00-6412-11eb-988e-c27487285e94.png)

Can you please verify?
Thanks.

**Comment by mikestead** [comment]
@ast-hao sorry to hear that. It seems to be working ok on my end, wondering if it could be a windows vs mac thing.

Could you add the `-v` (verbose) option and let me know what params are printed out for the lighthouse command. e.g. for this command

```
npx lighthouse-batch -p "--preset=desktop" -s web.dev -h --csv -v
```

I see the following logged

```
Lighthouse batch run begin for 1 site
1/1: Lighthouse analyzing 'https://web.dev'
"https://web.dev" --output json --output html --output csv --output-path "report/lighthouse/web_dev" --chrome-flags="--no-sandbox --headless --disable-gpu" --preset=desktop
```

<img width="597" alt="Screen Shot 2021-02-01 at 1 34 08 pm" src="https://user-images.githubusercontent.com/56844/106408239-272a0480-6492-11eb-8dea-60c01248aeef.png">

**Comment by ast-hao** [comment]
> @ast-hao sorry to hear that. It seems to be working ok on my end, wondering if it could be a windows vs mac thing.
> 
> First request is to double check your global version installed `lighthouse-batch --version`. This should be v7+.
> 
> After that if you could you add the `-v` (verbose) option and let me know what params are printed out for the lighthouse command. e.g. for this command
> 
> ```
> npx lighthouse-batch -p "--preset=desktop" -s web.dev -h --csv -v
> ```
> 
> I see the following logged
> 
> ```
> Lighthouse batch run begin for 1 site
> 1/1: Lighthouse analyzing 'https://web.dev'
> "https://web.dev" --output json --output html --output csv --output-path "report/lighthouse/web_dev" --chrome-flags="--no-sandbox --headless --disable-gpu" --preset=desktop
> ```
> 
> <img alt="Screen Shot 2021-02-01 at 1 34 08 pm" width="597" src="https://user-images.githubusercontent.com/56844/106408239-272a0480-6492-11eb-8dea-60c01248aeef.png">

Hi mikestead, I re-installed the latest lighthouse, at the end of the installation, it tells 2 packages updated, version 7.0.1, then the --preset=desktop in lighthouse-batch is working well now.
Sorry I just see your reply, cannot test now...
Thanks again for the batch tool!

**Comment by mikestead** [comment]
no worries, good to hear
