### ISSUE TITLE
Update Lighthouse to v7.3.0+ to fix vulnerability

### ISSUE THREAD

**Issue by pyymenta** [mikestead/lighthouse-batch#63]
Hello guys,

Lighthouse [v7.3.0](https://github.com/GoogleChrome/lighthouse/releases/tag/v7.3.0) was released some time ago.

The release notes includes the `jsonld` update to [its latest version](https://github.com/GoogleChrome/lighthouse/pull/12257)

It fixes this vulnerability described below:

https://npmjs.com/advisories/1650 

![image](https://user-images.githubusercontent.com/13206817/113053732-007d0700-917f-11eb-866e-afa85189820d.png)

**Comment by pyymenta** [comment]
Same related in GoogleChrome/lighthouse-ci#580

**Comment by I-Valchev** [comment]
+1 Would be great to get this fixed! Thanks!

**Comment by mikestead** [comment]
apologies for the delay, I've updated to point at the latest `v8.0.0` of lighthouse, released under `v8.0.0` of lighthouse-batch
