### ISSUE TITLE
Cannot Generate File & Score If URL Lengh is More Than 255 Characters

### ISSUE THREAD

**Issue by onurtr** [mikestead/lighthouse-batch#66]
Hi;

Thanks for this wonderful tool. We' ve a problem about some links that has more than 255 characters. We cannot generate score & save these kind of URLs. I think it' s because of Windows is allowing File Name' s lengh as maximum 255.

Is there a way to modify file name?

Kind regards.

**Comment by mikestead** [comment]
@onurtr thanks for the kind words and bug report, I've pushed `lighthouse-batch@8.0.1` which should fix the issue, let me know if you still run into problems
