### ISSUE TITLE
Multiple URLs via JSON

### ISSUE THREAD

**Issue by ccharlton** [mikestead/lighthouse-batch#7]
It'd be great to have the ability to point to a JSON path that lists the URLs to score. I'm trying to get scores for multiple main pages to a single website in bulk.

**Comment by mikestead** [comment]
@ccharlton sounds like a good idea. Just to check we're on the same page, the only addition you're after is the ability to point to a JSON file with an array of urls to cycle through?

**Comment by ccharlton** [comment]
Correct. It's a pain to retype URLs in a CLI, versus loading an external file for repeatability and portability.
