### ISSUE TITLE
Integration with lighthouse-ci

### ISSUE THREAD

**Issue by mgifford** [mikestead/lighthouse-batch#8]
I want to have the batch option, but just want the pass/fail option that you can get from lighthouse-ci.  Any way to just highlight the number in the results?

**Comment by mikestead** [comment]
@mgifford there's now a details section in the summary output thanks to @elsassph. Released under `v4.1.0`. I hope that covers your use case.

e.g. `summary.json`

```json
[
  {
    "url": "https://www.bbc.com",
    "name": "www_bbc_com",
    "file": "www_bbc_com.report.json",
    "score": "0.64",
    "detail": {
      "performance": 0.36,
      "accessibility": 0.87,
      "best-practices": 0.71,
      "seo": 0.96,
      "pwa": 0.31
    }
  }
]
```
