### ISSUE TITLE
windows script host error

### ISSUE THREAD

**Issue by WebVeteran** [mikestead/lighthouse-batch#9]
I am getting the following error in Windows 10.
Lighthouse CLI works fine though.

![image](https://user-images.githubusercontent.com/40175/48664852-60bdf300-ea73-11e8-9f29-93a8587e2014.png)

**Comment by WebVeteran** [comment]
The option `--use-global` is a way to get around the issue.

**Comment by elsassph** [comment]
You may need `node` to be the default application for executing JavaScript.

**Comment by mikestead** [comment]
@WebVeteran thanks for reporting this, we're tracking it over at #15
